#!/usr/bin/env bash
set -e
CONF="$PWD/.vagrant_ssh_config"
if [ ! -e "$CONF" ]; then
  vagrant ssh-config > "$CONF"
fi
function field {
  cat "$CONF" | grep "$1 " | awk '{print $2}' | tr -d '"'
}
exec fab \
  --no_agent \
  --no-keys \
  --disable-known-hosts \
  --user="$(field User)" \
  --password=vagrant \
  --hosts="$(field HostName)" \
  --port="$(field Port)" \
  "$@"
