#!/usr/bin/env bash
set -e
set -x
CONF=$(vagrant ssh-config)
function field {
  grep "$1 " <<<"$CONF" | awk '{print $2}' | tr -d '"'
}
exec fab \
  --no_agent \
  --no-keys \
  --disable-known-hosts \
  --user="$(field User)" \
  --password=vagrant \
  --hosts="$(field HostName)" \
  --port="$(field Port)" \
  "$@"
